title: "Atchatha – Data Science & Machine Learning Portfolio"
description: "Data Science projects, learning journey, and consulting. SQL • Python • Analytics."
url: "https://<yourusername>.github.io"
author:
  name: "Atchatha"
  email: "your-email@example.com"

# Social links for footer (fill the hrefs you have now; leave others blank or remove)
social:
  linkedin: "https://www.linkedin.com/in/atchathaluv2code/"
  github: "https://github.com/atchatha"
  medium: "https://medium.com/@akshathamurali95"
  upwork: "https://www.upwork.com/freelancers/~014471b0eb81906687"
  kaggle: "https://www.kaggle.com/atchatha"

# SEO / indexing
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# SEO tag config
# Add this EXACT string from Google Search Console when you verify tomorrow
google_site_verification: ""

# Analytics (optional). Add your GA4 Measurement ID (e.g., G-XXXXXXX) to enable.
google_analytics: ""

# Permalinks (SEO/GPT-friendly, readable)
permalink: /:title/
collections:
  posts:
    output: true
    permalink: /:title/

# Build settings
theme: null
markdown: kramdown

# Defaults to auto-add “Last updated”
defaults:
  - scope:
      path: ""
    values:
      last_modified: "{{ 'now' | date: '%Y-%m-%d' }}"
